name: panelista_chatbot
dependencies: 
  - python=3.13.0
  - pip
  - pip: 
    - django==5.1.2
    - djangorestframework==3.15.2
    - djangorestframework-simplejwt==5.3.1
    - groq==0.11.0
    - python-dotenv==1.0.1
    - cerebras-cloud-sdk==1.6.0
    - openai==1.51.2
    - reportlab==4.2.5
    - beautifulsoup4==4.12.3
