# Generated by Django 5.1.2 on 2024-10-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='topics',
            field=models.TextField(blank=True),
        ),
    ]
